
services:
  db:
    image: postgres:latest
    container_name: task-backend-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: your_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
